/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.*;
import IOData.GenericFileHandler;
import java.util.*;

/**
 *
 * @author haong
 */
public class ThongKeGD extends javax.swing.JFrame {

    String hdxFile = "src/Data/HoaDonXuat.dat";
    String hdnFile = "src/Data/HoaDonNhap.dat";
    String sachFile = "src/Data/Books.dat";
    String nvFile = "src/Data/Accounts.dat";
    GenericFileHandler<HoaDonXuat> hdxHandler = new GenericFileHandler<>(hdxFile);
    GenericFileHandler<HoaDonNhap> hdnHandler = new GenericFileHandler<>(hdnFile);
    GenericFileHandler<Sach> readBooks = new GenericFileHandler<>(sachFile);
    GenericFileHandler<TaiKhoan> readAccounts = new GenericFileHandler<>(nvFile);
    List<HoaDonXuat> hdx = hdxHandler.readFromFile();
    List<HoaDonNhap> hdn = hdnHandler.readFromFile();
    List<Sach> ms = readBooks.readFromFile();
    List<TaiKhoan> nVien = readAccounts.readFromFile();
    String[] data;
    
    /**
     * Creates new form ThongKeGD
     */
    public ThongKeGD() {
        initComponents();
        calData();
    }
    
    public final void calData() {
        long ttx = 0, ttn = 0;
        int slnv = 0, 
                slsn = 0, 
                slsx = 0,
                slhdn = 0,
                slhdx = 0;
        for (HoaDonXuat ds : hdx) {
            ttx += ds.getThanhTien();
            slsx += ds.getSoLuongX();
            slhdx++;
        }
        for (HoaDonNhap ds : hdn) {
            ttn += ds.getThanhTien();
            slsn += ds.getSoLuongN();
            slhdn++;
        }
        for (TaiKhoan ds : nVien) {
            slnv++;
        }
        if ((slsn - slsx) > 0) {
            txtST.setText(Integer.toString(slsn - slsx));
        } else {
            txtST.setText("0");
        }

        txtHDN.setText(Integer.toString(slhdn));
        txtHDX.setText(Integer.toString(slhdx));
        txtSN.setText(Integer.toString(slsn));
        txtSX.setText(Integer.toString(slsx));
        txtTX.setText(Long.toString(ttx));
        txtTN.setText(Long.toString(ttn));
        txtNV.setText(Integer.toString(slnv));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnHeader = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblHDN = new javax.swing.JLabel();
        txtHDN = new javax.swing.JLabel();
        lblSN = new javax.swing.JLabel();
        txtSN = new javax.swing.JLabel();
        txtTN = new javax.swing.JLabel();
        lblTN = new javax.swing.JLabel();
        lblHDX = new javax.swing.JLabel();
        txtHDX = new javax.swing.JLabel();
        txtSX = new javax.swing.JLabel();
        lblSX = new javax.swing.JLabel();
        txtTX = new javax.swing.JLabel();
        lblTX = new javax.swing.JLabel();
        lblST = new javax.swing.JLabel();
        txtST = new javax.swing.JLabel();
        lblNV = new javax.swing.JLabel();
        txtNV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("THỐNG KÊ");
        setResizable(false);

        pnHeader.setBackground(new java.awt.Color(204, 204, 204));

        lblHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblHeader.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("THỐNG KÊ");

        btnBack.setBackground(new java.awt.Color(0, 204, 204));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHeaderLayout.createSequentialGroup()
                .addGroup(pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblHDN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHDN.setText("Số lượng hóa đơn nhập vào");

        txtHDN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHDN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHDN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHDN.setEnabled(false);
        txtHDN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblSN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSN.setText("Số lượng sách nhập vào");

        txtSN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSN.setEnabled(false);
        txtSN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTN.setEnabled(false);
        txtTN.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTN.setText("Tổng tiền nhập vào");

        lblHDX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHDX.setText("Số lượng hóa đơn xuất ra");

        txtHDX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHDX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHDX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHDX.setEnabled(false);
        txtHDX.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtSX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSX.setEnabled(false);
        txtSX.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblSX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSX.setText("Số lượng sách xuất ra");

        txtTX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTX.setEnabled(false);
        txtTX.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblTX.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTX.setText("Tổng tiền xuất ra");

        lblST.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblST.setText("Số lượng sách còn tồn kho");

        txtST.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtST.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtST.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtST.setEnabled(false);
        txtST.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNV.setText("Số lượng nhân viên");

        txtNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNV.setEnabled(false);
        txtNV.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSN, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSN, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTN, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTN, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHDX, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHDX, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSX, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSX, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTX, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTX, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblST, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtST, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNV, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNV, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHDN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHDX, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHDX, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSX, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSX, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTX, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTX, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtST, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblST, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNV, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKeGD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblHDN;
    private javax.swing.JLabel lblHDX;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblNV;
    private javax.swing.JLabel lblSN;
    private javax.swing.JLabel lblST;
    private javax.swing.JLabel lblSX;
    private javax.swing.JLabel lblTN;
    private javax.swing.JLabel lblTX;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JLabel txtHDN;
    private javax.swing.JLabel txtHDX;
    private javax.swing.JLabel txtNV;
    private javax.swing.JLabel txtSN;
    private javax.swing.JLabel txtST;
    private javax.swing.JLabel txtSX;
    private javax.swing.JLabel txtTN;
    private javax.swing.JLabel txtTX;
    // End of variables declaration//GEN-END:variables
}
